spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation:true

  datasource:
    url: jdbc:postgresql://localhost:5432/policybazar
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver


server:
  port: 9090