spring:
  jpa: 
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        formatSql: true
        jdbc:
          lob:
            non-contextual-creation: true
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    
            
  datasource:
    url: jdbc:postgresql://localhost:5432/policybazar
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver


server:
  port: 9090